### ISSUE TITLE
Modify Contact Page - Design and Colour Changes

### ISSUE THREAD

**Issue by Khizarshah01** [Yashdon999/Resume-Genrator#16]
**Description:**
Currently, the Contact page on our website has a basic design and color scheme that does not match the overall look and feel of the site. I would like to propose modifying the design and color of the Contact page to improve its visual appeal and make it more user-friendly.

**Proposed Changes:**
- Add a background image or pattern to the page to make it visually interesting and engaging.
- Change the font and font size to make the text more readable.
- Use a consistent color scheme throughout the page to make it more visually cohesive.
- Incorporate more white space and use of grids to create a clear visual hierarchy.

**Expected Outcome:**
The modified Contact page will have an improved design and color scheme that matches the overall look and feel of the website. It will be visually engaging and easy to read, making it more user-friendly for visitors who wish to contact us.

Any feedback or suggestions are welcome.

**Comment by munnokd** [comment]
Can I work on this issue?

**Comment by Khizarshah01** [comment]
Sure, that would be great! Thank you for showing interest in this issue. Please feel free to start working on it and let me know if you have any questions or need any help. Looking forward to seeing your contributions!

**Comment by munnokd** [comment]
Ok, I am going to start working on it.

**Comment by munnokd** [comment]
I made this design of contact page. Please say if any changes in this design or I will make pull request for this?
![image](https://user-images.githubusercontent.com/81804004/222953215-05ebc870-aea6-409c-b075-12bf6d56ba43.png)

**Comment by Khizarshah01** [comment]
Thank you for your work on the contact page design! It looks great. I would like to request one additional change if possible. Could you add a hover effect to the button? If you're willing to make that change, I would be happy to review and merge your pull request. Thank you again for your help!

**Comment by munnokd** [comment]
Yes, I will make some additional changes and I had done hover effect of button.

**Comment by munnokd** [comment]
Hey bro I had done this issue. Please see my pull request and merge it.

**Comment by Khizarshah01** [comment]
Work Done!
