### ISSUE TITLE
Custom color picker causing layout shift in resume body

### ISSUE THREAD

**Issue by ShashwatAgrawal20** [Yashdon999/Resume-Genrator#19]
When a user selects the custom color picker option on the **resume page**, the layout of the resume body shifts significantly, resulting in an unprofessional and unpleasant appearance, which can impact the overall presentation of the site.
 
 
 Additionally, we understand that users may have individual preferences when it comes to color schemes and may prefer options that are not included in the **pre-configured selection**. Therefore, we are open to suggestions for additional color options that can be added to the selection or some change in the current one. If users have found alternative color schemes that work well with the resume format and would like to suggest them for inclusion, we encourage them to share their ideas with us.

![image](https://user-images.githubusercontent.com/72117025/226963855-c7c52341-3a7d-4dbe-ba53-cccc0e1160f4.png)

**Comment by minnayu** [comment]
hello! Can I work on this issue?

**Comment by ShashwatAgrawal20** [comment]
Sure go ahead. 👍

**Comment by ShashwatAgrawal20** [comment]
hey! @minnayu are you still working on this ?

**Comment by minnayu** [comment]
@ShashwatAgrawal20 yes! will hopefully finish by tuesday
